---
title: "Prostate Cancer Analyses"
author: "Karthik Natarajan and Thomas Falconer"
date: "9/15/2021"
output: html_document

params:
 cohortDatabaseSchema: x
 cohortId: 1775947
 connection: x
 minCellCount: 5
 outputFolder: x

---

```{r message=FALSE, warning=FALSE}
library(devtools)
library(dplyr)
library(ggplot2)
library(tidyr)
library(ggrepel)
library(lubridate)
library(forcats)
library(RColorBrewer)
```

```{r message=FALSE, warning=FALSE}
outputFolder <- params$outputFolder
minCellCount <- params$minCellCount
cohortId <- params$cohortId
time_window_for_interventions <- 365

cancerCohortDataTable <- getCancerDataSet(params$cohortDatabaseSchema, params$cohortId, params$connection)

writeLines(paste("outputFolder = ", outputFolder, "\n",
      "minCellCount = ", minCellCount, "\n",
      "cohortId = ", cohortId, "\n",
       "time_window_for_interventions = ", time_window_for_interventions))

```

```{r message=FALSE, warning=FALSE}
  cancerSpecificVectors <- getVectorsForSpecificCancer(cohortId)
  cancerSpecificVectors

  #function to produce interventions per patient
  augmentedCancerDataSet <- augmentCancerDataSet(cancerCohortDataTable = cancerCohortDataTable,
                                               interventionsVector = cancerSpecificVectors$interventions,
                                               drugVector = cancerSpecificVectors$drugs_vector,
                                               timeWindowForInterventions = time_window_for_interventions)

  #clear out previous run data
  if (file.exists(outputFolder)) {
    unlink(outputFolder, recursive = TRUE)
  } else {
    dir.create(outputFolder, recursive = TRUE)
  }
```
```{r message=FALSE, warning=FALSE}
# Percent distribution of intervention types, by year
plot <- examineInterventionsPerYear(augmentedCancerDataSet, outputFolder, minCellCount)
plot
```

```{r message=FALSE, warning=FALSE}
#plot 1
#counting distinct diagnoses by year
plot <- examineDxPerYear(augmentedCancerDataSet, outputFolder, minCellCount)
plot
```

```{r message=FALSE, warning=FALSE}
#plot 2
#average age at diagnosis by year
plot <- examineAvgAgeAtDx(augmentedCancerDataSet, outputFolder, minCellCount)
plot
```
```{r message=FALSE, warning=FALSE}
#average drug classes by year
plot <- examineAvgNumDrugsByTreatmentClass(augmentedCancerDataSet, outputFolder, minCellCount)
plot
```
```
## All the below plots are based on the index date of each patient and the earliest drug intervention for irrespective of the year the drug (intervention) was taken.
```

```{r message=FALSE, warning=FALSE}
#plot 11 - ADT plot
  #Endocrine distribution in the adjuvant setting
  #selecting for patients who are labeled as having adjuvant
adjuvant_endrocrine_records <- cancerCohortDataTable %>%
  filter(neoadjuvant == '0', generic_drug_name %in% cancerSpecificVectors$endocrine_drugs) %>%
  distinct(person_id, dx_year, generic_drug_name, intervention_date) %>%
  arrange(dx_year, person_id, intervention_date) %>%
  group_by(person_id) %>%
  slice(1)
plot <- examinePercentEndocrineForAdjuvantTherapy(adjuvant_endrocrine_records, outputFolder, minCellCount)
plot
```

```{r message=FALSE, warning=FALSE}
#Endocrine distribution in the neoadjuvant setting
neoadjuvant_endrocrine_records <- cancerCohortDataTable %>%
  filter(neoadjuvant == '1', generic_drug_name %in% cancerSpecificVectors$endocrine_drugs) %>%
  distinct(person_id, dx_year, generic_drug_name, intervention_date) %>%
  arrange(dx_year, person_id, intervention_date) %>%
  group_by(person_id) %>%
  slice(1)
plot <- examinePercentEndocrineForNeoAdjuvantTherapy(neoadjuvant_endrocrine_records, outputFolder, minCellCount)
plot
```
```{r message=FALSE, warning=FALSE}
#first line chemotherapy in the adjuvant setting
adjuvant_chemo_records <- cancerCohortDataTable %>%
  filter(neoadjuvant == '0', generic_drug_name %in% cancerSpecificVectors$chemo_drugs) %>%
  distinct(person_id, dx_year, generic_drug_name, intervention_date) %>%
  arrange(dx_year, person_id, intervention_date) %>%
  group_by(person_id) %>%
  slice(1)
plot <- examinePercentChemoForAdjuvantTherapy(adjuvant_chemo_records, outputFolder, minCellCount)
plot
```
```{r message=FALSE, warning=FALSE}
#first line chemotherapy in the neoadjuvant setting
neoadjuvant_chemo_records <- cancerCohortDataTable %>%
  filter(neoadjuvant == '1', generic_drug_name %in% cancerSpecificVectors$chemo_drugs) %>%
  distinct(person_id, dx_year, generic_drug_name, intervention_date) %>%
  arrange(dx_year, person_id, intervention_date) %>%
  group_by(person_id) %>%
  slice(1)
plot <- examinePercentChemoForNeoAdjuvantTherapy(neoadjuvant_chemo_records, outputFolder, minCellCount)
plot
```
